# Generated by Django 3.1.5 on 2021-02-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receiptionist',
        ),
    ]
