# Generated by Django 3.1.5 on 2021-02-19 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0002_delete_receiptionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200)),
                ('issue_description', models.TextField()),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Employees Attendance Record', 'verbose_name_plural': 'Employees Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee Detail', 'verbose_name_plural': 'Employees Details'},
        ),
    ]
