# Generated by Django 3.1.5 on 2021-02-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0003_auto_20210219_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_phone', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=200)),
                ('highest_education_level', models.CharField(max_length=200)),
                ('education_specifilization', models.CharField(max_length=200, verbose_name='e.g Bsc. Medicine')),
                ('postal_code', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
            },
        ),
    ]
