# Generated by Django 3.1.5 on 2021-02-19 10:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0004_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.attendance')),
            ],
            options={
                'verbose_name': 'Employees Checkout Detail',
                'verbose_name_plural': 'Employees Checkout Details',
            },
        ),
    ]
