# Generated by Django 3.1.5 on 2021-02-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0006_auto_20210219_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Employees Checkin Record', 'verbose_name_plural': 'Employees Checkin Records'},
        ),
    ]
