# Generated by Django 3.1.5 on 2021-02-19 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0009_delete_firedemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiredEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employment_date', models.DateTimeField()),
                ('position_worked', models.CharField(max_length=200)),
                ('firing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('firing_reason', models.TextField()),
                ('employee_comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Fired Employee',
                'verbose_name_plural': 'Fired Employees',
            },
        ),
    ]
