# Generated by Django 3.1.5 on 2021-02-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0010_firedemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Pharmacy', 'Pharmacy'), ('Finance', 'Finance'), ('Laboratory', 'Laboratory'), ('Procurement', 'Procurement')], max_length=200, null=True),
        ),
    ]
