# Generated by Django 3.1.5 on 2021-02-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0011_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='education_specifilization',
            field=models.CharField(max_length=200, verbose_name='Education Specialization'),
        ),
    ]
