# Generated by Django 3.1.5 on 2021-02-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0012_auto_20210219_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='education_specifilization',
            new_name='education_specialization',
        ),
    ]
