# Generated by Django 3.1.5 on 2021-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0013_auto_20210224_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
