# Generated by Django 3.1.5 on 2021-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0014_appointment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
