# Generated by Django 3.1.5 on 2021-02-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0017_auto_20210225_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hair_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='height',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='skin_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
