# Generated by Django 3.1.5 on 2021-02-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0018_auto_20210225_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='places_worked',
            field=models.TextField(),
        ),
    ]
