# Generated by Django 3.1.5 on 2021-02-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0020_auto_20210225_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
