# Generated by Django 3.1.5 on 2021-02-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0021_employeeleave_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleave',
            old_name='approved',
            new_name='approval_status',
        ),
    ]
