# Generated by Django 3.1.5 on 2021-02-26 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0022_auto_20210225_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
