# Generated by Django 3.1.5 on 2021-02-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'verbose_name_plural': 'Employees Salaries'},
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='employee',
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.employeesalary'),
        ),
    ]
