# Generated by Django 3.1.5 on 2021-02-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_auto_20210222_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='payment_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
