# Generated by Django 3.1.5 on 2021-02-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_salarypayment_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.employeesalary'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_number',
            field=models.CharField(max_length=100),
        ),
    ]
