# Generated by Django 3.1.5 on 2021-02-23 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0013_auto_20210222_1746'),
        ('HumanResource', '0012_auto_20210219_1847'),
        ('Finance', '0004_auto_20210222_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_university_attended', models.CharField(max_length=500)),
                ('highest_education_level', models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ('Masters Degree', 'Masters Degree'), ('PhD', 'PhD')], max_length=50)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Day', 'Day'), ('Night', 'Night')], max_length=50)),
                ('schools_attended', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=500)),
                ('places_worked', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.employee')),
            ],
            options={
                'verbose_name_plural': 'Finance Officers',
            },
        ),
        migrations.CreateModel(
            name='HealthBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FloatField()),
                ('mode_of_payment', models.CharField(choices=[('Cash Payment', 'Cash Payment'), ('Wire Transfer', 'Wire Transfer'), ('Cheque Payment', 'Cheque Payment'), ('Mobile Money', 'Mobile Money')], max_length=50)),
                ('paid_on', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.financeofficer')),
            ],
            options={
                'verbose_name_plural': 'Patients Bills',
            },
        ),
    ]
