# Generated by Django 3.1.5 on 2021-02-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0001_initial'),
        ('Finance', '0005_financeofficer_healthbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_code', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('sales_date', models.DateTimeField()),
                ('date_submitted', models.DateTimeField()),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.financeofficer')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.pharmacist')),
            ],
            options={
                'verbose_name_plural': 'Drug Sales',
            },
        ),
    ]
