# Generated by Django 3.1.5 on 2021-02-05 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HumanResource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateTimeField()),
                ('graduation_year', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_university_attended', models.CharField(max_length=500)),
                ('highest_education_level', models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ('Masters Degree', 'Masters Degree'), ('PhD', 'PhD')], max_length=50)),
                ('schools_attended', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=500)),
                ('places_worked', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_office', models.CharField(max_length=200)),
                ('number_of_workers', models.IntegerField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.director')),
            ],
        ),
    ]
