# Generated by Django 3.1.5 on 2021-02-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0007_auto_20210219_1353'),
        ('Staff', '0004_receiptionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('date_appointed', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.employee')),
            ],
            options={
                'verbose_name': 'All Staff Member',
                'verbose_name_plural': 'All Staff Members',
            },
        ),
    ]
