# Generated by Django 3.1.5 on 2021-02-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0008_appointment_approvedappointment_employeeleave_firedemployee_pendingappointment_receiptionist'),
        ('Staff', '0005_administrativestaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Department Director',
                'verbose_name_plural': 'Department Directors',
            },
        ),
        migrations.RemoveField(
            model_name='director',
            name='department',
        ),
        migrations.RemoveField(
            model_name='director',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='receiptionist',
            name='department',
        ),
        migrations.RemoveField(
            model_name='receiptionist',
            name='employee',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='number_of_workers',
            new_name='number_of_employees',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_office',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AdministrativeStaff',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Receiptionist',
        ),
        migrations.AddField(
            model_name='departmentdirector',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.department'),
        ),
        migrations.AddField(
            model_name='departmentdirector',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.employee'),
        ),
    ]
