# Generated by Django 3.1.5 on 2021-02-24 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0010_auto_20210219_1830'),
        ('Patients', '0013_auto_20210222_1746'),
        ('HumanResource', '0012_auto_20210219_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_university_attended', models.CharField(max_length=500)),
                ('highest_education_level', models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ('Masters Degree', 'Masters Degree'), ('PhD', 'PhD')], max_length=50)),
                ('schools_attended', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=500)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Day', 'Day'), ('Night', 'Night')], max_length=50)),
                ('places_worked', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.employee')),
            ],
            options={
                'verbose_name_plural': 'Lab Technicians',
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField()),
                ('test_results', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctor')),
                ('test_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Laboratory.labtechnician')),
            ],
            options={
                'verbose_name_plural': 'Lab Tests',
            },
        ),
    ]
