# Generated by Django 3.1.5 on 2021-02-22 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HumanResource', '0012_auto_20210219_1847'),
        ('Procurement', '0001_initial'),
        ('Patients', '0013_auto_20210222_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('received_quantity', models.FloatField()),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_university_attended', models.CharField(max_length=500)),
                ('highest_education_level', models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ('Masters Degree', 'Masters Degree'), ('PhD', 'PhD')], max_length=50)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Day', 'Day'), ('Night', 'Night')], max_length=50)),
                ('schools_attended', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=500)),
                ('places_worked', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DrugSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_time', models.DateTimeField()),
                ('quantity_sold', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.drug')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patients.prescription')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.pharmacist')),
            ],
            options={
                'verbose_name': 'Drugs Sale',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.pharmacist'),
        ),
        migrations.AddField(
            model_name='drug',
            name='supplied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.supplier'),
        ),
    ]
