# Generated by Django 3.1.5 on 2021-02-19 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0008_appointment_approvedappointment_employeeleave_firedemployee_pendingappointment_receiptionist'),
        ('Hospital', '0003_delete_receiptionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_office', models.CharField(max_length=200)),
                ('number_of_workers', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='department',
        ),
        migrations.RemoveField(
            model_name='psychiatrist',
            name='department',
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_university_attended', models.CharField(max_length=500)),
                ('highest_education_level', models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ('Masters Degree', 'Masters Degree'), ('PhD', 'PhD')], max_length=50)),
                ('schools_attended', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=500)),
                ('places_worked', models.TextField()),
                ('date_appointed', models.DateTimeField()),
                ('department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.employee')),
            ],
            options={
                'verbose_name': 'Department Director',
            },
        ),
        migrations.AlterField(
            model_name='ward',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.department'),
        ),
    ]
