# Generated by Django 3.1.5 on 2021-02-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0011_employee_department'),
        ('Hospital', '0004_auto_20210219_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorChairperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateTimeField()),
                ('department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.department')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.employee')),
            ],
            options={
                'verbose_name': 'Department Director',
            },
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
