# Generated by Django 3.1.5 on 2021-02-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0011_employee_department'),
        ('Hospital', '0005_auto_20210219_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectorChairperson',
            new_name='DepartmentChairperson',
        ),
    ]
