# Generated by Django 3.1.5 on 2021-02-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_auto_20210219_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentchairperson',
            old_name='name',
            new_name='chairperson',
        ),
    ]
