# Generated by Django 3.1.5 on 2021-02-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_auto_20210219_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
