# Generated by Django 3.1.5 on 2021-02-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0008_delete_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('occupied_capacity', models.IntegerField()),
                ('occupation_status', models.CharField(choices=[('Fully Occupied', 'Fully Occupied'), ('Not Fully Occupied', 'Not Fully Occupied'), ('Empty', 'Empty')], max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.department')),
                ('nurse_on_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.nurse')),
            ],
        ),
    ]
