# Generated by Django 3.1.5 on 2021-02-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_ward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentchairperson',
            options={'verbose_name': 'Department Chairperson'},
        ),
    ]
