# Generated by Django 3.1.5 on 2021-02-22 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0004_auto_20210222_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvisit',
            options={'verbose_name': 'Patients Visits Detail'},
        ),
        migrations.AddField(
            model_name='patientcomment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
