# Generated by Django 3.1.5 on 2021-02-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0006_healthhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthhistory',
            options={'verbose_name': 'Patient Healthy History', 'verbose_name_plural': 'Patient Healthy Historis'},
        ),
    ]
