# Generated by Django 3.1.5 on 2021-02-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0007_auto_20210222_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthhistory',
            options={'verbose_name': 'Patient Healthy History', 'verbose_name_plural': 'Patient Healthy Histories'},
        ),
    ]
