# Generated by Django 3.1.5 on 2021-02-22 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_auto_20210219_1830'),
        ('Patients', '0008_auto_20210222_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_drug', models.CharField(max_length=500)),
                ('date_prescribed', models.DateTimeField(default=django.utils.timezone.now)),
                ('prescription_start_date', models.DateTimeField()),
                ('prescription_end_date', models.DateTimeField()),
                ('prescription_notes', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctor')),
            ],
            options={
                'verbose_name': 'Patients Drug Prescription',
            },
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
