# Generated by Django 3.1.5 on 2021-02-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0009_auto_20210222_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvisit',
            old_name='name',
            new_name='patient',
        ),
    ]
