# Generated by Django 3.1.5 on 2021-02-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_auto_20210219_1830'),
        ('Patients', '0010_auto_20210222_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('date_recorded', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
            options={
                'verbose_name': 'Patients Health Record',
            },
        ),
        migrations.CreateModel(
            name='AdmittedPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admitted', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.ward')),
            ],
            options={
                'verbose_name': 'Admitted Patient',
            },
        ),
    ]
