# Generated by Django 3.1.5 on 2021-02-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0012_patientdischarge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdischarge',
            options={'verbose_name': 'Discharged Patient'},
        ),
    ]
